repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    #- id: check-added-large-files - disabled, bug in v0.9.5?
    - id: check-yaml
