version: '2'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./src/docker/run/Dockerfile
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    links:
      - "db"
  db:
    container_name: db
    image: postgres:9.5.3
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
