# Build the application and regenerate the Hibernate mapping

portaldb:
  image: postgres:9.4.5
  container_name: portaldb
  ports:
    - "55432:5432"
  volumes:
    - ./src/test/db/sql:/docker-entrypoint-initdb.d/
  environment:
    POSTGRES_PASSWORD: test

portal-backend:
  build: .
  volumes:
    - ./:/portal/
    - ./.m2/:/root/.m2/
  links:
    - portaldb
  ports:
    - "8080:8080"
