# Configuration for development purposes

### EMBEDDED SERVER CONFIGURATION ###
server:
  servlet:
    contextPath: "/services"
  port: 8080
  forward-headers-strategy: native

### DATABASE CONFIGURATION ###
spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5433/portal"
    username: "portal"
    password: "portalpwd"
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: mippublic
            client-secret: a62c2031-14ee-4a20-8271-a6513982bebf
            provider: keycloak
            scope: openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: https://iam.ebrains.eu/auth/realms/MIP

### AUTHENTICATION ###
authentication:
  enabled: 1
  all_datasets_allowed_claim: research_dataset_all
  all_experiments_allowed_claim: research_experiment_all
  dataset_claim_prefix: research_dataset_

### EXTERNAL SERVICES ###
services:
  algorithmsUpdateInterval: 100
  exareme2:
    algorithmsUrl: "http://127.0.0.1:5000/algorithms"
    attributesUrl: "http://127.0.0.1:5000/data_models_attributes"
    cdesMetadataUrl: "http://127.0.0.1:5000/cdes_metadata"

### EXTERNAL FILES ###
# Files are loaded from the resources
files:
  disabledAlgorithms_json: "classPath:/disabledAlgorithms.json"

frontend:
  base-url: "http://localhost:4200"
