# Configuration for development purposes


### EMBEDDED SERVER CONFIGURATION ###
server:
  servlet:
    contextPath: "/services"
  port: 8080
  forward-headers-strategy: native


### LOG LEVELS ###
logging:
  level:
    root: "INFO"
    eu:
      hbp: "DEBUG"


### DATABASE CONFIGURATION ###
spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5433/portal"
    username: "portal"
    password: "portalpwd"
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: MIP
            client-secret: dae83a6b-c769-4186-8383-f0984c6edf05
            provider: keycloak
            scope: openid
            redirect-uri: http://172.17.0.1/${server.servlet.contextPath}/login/oauth2/code/MIP
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://172.17.0.1/auth/realms/MIP


### AUTHENTICATION ###
authentication:
  enabled: 0
  all_datasets_allowed_claim: research_dataset_all
  all_experiments_allowed_claim: research_experiment_all
  dataset_claim_prefix: research_dataset_


### EXTERNAL SERVICES ###
services:
  algorithmsUpdateInterval: 100
  exareme2:
    algorithmsUrl: "http://127.0.0.1:5000/algorithms"
    attributesUrl: "http://127.0.0.1:5000/data_models_attributes"
    cdesMetadataUrl: "http://127.0.0.1:5000/cdes_metadata"


### EXTERNAL FILES ###
# Files are loaded from the resources
files:
  disabledAlgorithms_json: "classPath:/disabledAlgorithms.json"
