# Configuration template for the portal running inside a Docker container

spring:
  datasource:
    url: jdbc:postgresql://172.22.0.1:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  resources:
      chain:
        enabled: true

security:
  enabled: false

hbp:
  client:
    clientId: 996f97c5-a3ca-460e-b18b-00df3e2be89a
    clientSecret: aD0Tueb3KkNkcZqZgQbNyDWgnM95IfZ0xPCQ_6Z9dQNHXY00RIrnAD_m7sNJh1oofYSX8aHkl72MkwI0K626Ug
    accessTokenUri: https://services.humanbrainproject.eu/oidc/token
    userAuthorizationUri: https://services.humanbrainproject.eu/oidc/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://services.humanbrainproject.eu/oidc/userinfo

logging:
  level:
    org.springframework.security: DEBUG

server:
  contextPath: /services
  port: 8080
  use-forward-headers: true
  session:
    timeout: 2592000

workflow:
  experimentUrl: http://172.22.0.1:8087/experiment
  listMethodsUrl: http://172.22.0.1:8087/list-methods
  miningMipUrl: http://172.22.0.1:8087/mining
  miningExaremeUrl: http://hbps2.chuv.ch:9090/mining/query

frontend:
  redirect:
    url: http://frontend/home

authentication:
  enabled: 0
